# Spring properties
spring:
  application:
     name: client

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false

# HTTP Server
server:
  port: 8080