
server:
  port: 8080

ribbon:
  eureka:
    enabled: false
  ActiveConnectionsLimit: 10
  ConnectTimeout: 3000
  ReadTimeout: 3000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0
  ServerListRefreshInterval : 1000
  listOfServers: localhost:9000

hystrix:
  command:
    default:
      fallback.enabled: false
      circuitBreaker.enabled: false
      metrics.rollingPercentile.enabled: false
      execution.isolation.thread.interruptOnTimeout: true
      execution.isolation.thread.timeoutInMilliseconds: 200
  threadpool:
    default:
      coreSize: 20